[versions]

fabric-loader = "0.16.10"
fabric-language-kotlin = "1.13.4+kotlin.2.2.0"
fabric-api = "0.133.4"

kotlin = "2.2.0"
kotlin-symbol-processor = "2.2.0-2.0.2"
keval = "1.1.1"
gson = "2.12.1"

resourceful-config-kotlin = "3.5.15"

# Dependencies
skyblockapi = "4.0.0-beta.5"
hypixelapi = "1.0.1+build.1+mc1.21"
placeholders = "2.6.1+1.21.5"
rei = "20.0.811"

meowdding-remote-repo = "1.0.8"
meowdding-ktmodules = "1.0.6"
meowdding-ktcodecs = "1.1.5"
meowdding-patches = "1.0.8"
meowdding-auto-mixins = "1.0.5"

moulberry-mixinconstraints = "1.0.8"

[libraries]

fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
fabric-language-kotlin = { module = "net.fabricmc:fabric-language-kotlin", version.ref = "fabric-language-kotlin" }

skyblockapi = { module = "tech.thatgravyboat:skyblock-api", version.ref = "skyblockapi" }
hypixelapi = { module = "maven.modrinth:hypixel-mod-api", version.ref = "hypixelapi" }
placeholders = { module = "eu.pb4:placeholder-api", version.ref = "placeholders" }
rei = { module = "me.shedaniel:RoughlyEnoughItems-api-fabric", version.ref = "rei" }

resourceful-config-kotlin = { module = "com.teamresourceful.resourcefulconfigkt:resourcefulconfigkt-fabric-1.21.5", version.ref = "resourceful-config-kotlin" }

meowdding-ktmodules = { module = "me.owdding.ktmodules:KtModules", version.ref = "meowdding-ktmodules" }
meowdding-ktcodecs = { module = "me.owdding.ktcodecs:KtCodecs", version.ref = "meowdding-ktcodecs" }
meowdding-patches = { module = "me.owdding.patches:patches", version.ref = "meowdding-patches" }
meowdding-remote-repo = { module = "me.owdding.repo:remote-repo", version.ref = "meowdding-remote-repo" }
moulberry-mixinconstraints = { module = "com.moulberry:mixinconstraints", version.ref = "moulberry-mixinconstraints" }

kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
keval = { module = "com.notkamui.libs:keval", version.ref = "keval" }

gson = { module = "com.google.code.gson:gson", version.ref = "gson" }

[plugins]
meowdding-auto-mixins = { id = "me.owdding.auto-mixins", version.ref = "meowdding-auto-mixins" }
kotlin-symbol-processor = { id = "com.google.devtools.ksp", version.ref = "kotlin-symbol-processor" }
